openapi: 3.0.1
info:
  title: Nuapay Organisation Service API Specification
  description: Swagger Spec for the Organisations, Users and API Access Management Service
  contact:
    name: Nuapay
    email: api.support@nuapay.com
  license:
    name: Nuapay
    url: https://sentenial.com
  version: 1.17.2
  x-logo:
    backgroundColor: '#FFFFFF'
    url: https://www.nuapay.com/wp-content/uploads/2018/04/nuapay.svg
servers:
  - url: https://api.nuapay.com/cust
tags:
  - name: Organisation Management Service
    description: |-
      Organisation Management Service allows requesting user to onboard, view and update child organisations (Customers, Partners) and in particular allows to:
      - Retrieve organisation details and linked services
paths:
  /organisations:
    get:
      tags:
        - Organisation Management Service
      summary: List Child Organisations
      description: List Organisations
      operationId: listChildOrganisationsUsingGET
      parameters:
        - name: name
          in: query
          description: Filter by the Organisation Name. Partial match supported.
          schema:
            type: string
        - name: customerdefinedreference
          in: query
          description: Filter by the Customer Defined Reference
          schema:
            type: string
        - name: recursive
          in: query
          description: Search for all child organisations in the hierarchy for requested_org_id (instead of one level deep).
          schema:
            type: boolean
            default: false
        - name: vatnumber
          in: query
          description: VAT ID of the organisation
          schema:
            type: string
        - name: country
          in: query
          description: ISO 3166 ALPHA2 country code.
          schema:
            pattern: ^[A-Z]{2,2}$
            type: string
        - name: status
          in: query
          description: Organisation status.
          schema:
            enum:
              - ACTIVE
              - PENDING
              - DISABLED
        - name: organisationid
          in: query
          description: Organisation IDs.
          required: false
          schema:
            type: array
            items:
              type: string
        - name: organisationtype
          in: query
          description: Organisation Type.
          schema:
            enum:
              - PARTNER_GROUP
              - PARTNER
              - MERCHANT
        - name: pagenumber
          in: query
          description: 'Holds page number to be returned. Default: 1.'
          schema:
            type: integer
            format: int32
            default: 1
        - name: pagesize
          in: query
          description: 'Holds page size to be returned. Default: 20. Maxsize Default: 100.'
          schema:
            type: integer
            format: int32
            default: 20
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganisationsListResponseEnvelope'
              example:
                uri: /organisations
                data:
                  - id: 6bee3razby
                    uri: /organisations/6bee3razby
                    parentId: j98dn3veac
                    name: Company Limited
                    address:
                      streetName: Four Courts
                      postCode: D02N820
                      townName: Dublin 2
                    contact:
                      firstName: John
                      lastName: Smith
                      email: john.smith@email.com
                    country: IE
                    vatID: IE9S99999L
                    customerDefinedReference: 18a7ac1c-410f-4755-9d34-c5de42cdbfff
                    status: ACTIVE
                    organisationType: PARTNER
                    creationDateTime: 2022-05-19T10:32:01Z
                    lastUpdateDateTime: 2022-05-19T11:32:01Z
                    links:
                      - resourceType: openbanking
                        uri: /tpp/organisations/6bee3razby/config
                page:
                  pageNumber: 1
                  pageSize: 10
                  totalElements: 1
                  totalPages: 1
                sort: []
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                returnCode: ORG0000
                returnDescription: Validation errors occurred. Please see details.
                details:
                  code: ORG0006
                  description: Field is invalid.
                  field: pageSize
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example: {}
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example: {}
        405:
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example: {}
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                returnCode: ORG0000
                returnDescription: Validation errors occurred. Please see details.
                details:
                  code: ORG0008
                  description: Max Page size is exceeded.
                  field: pageSize
        429:
          description: Too Many Requests
          headers:
            Retry-After:
              description: Number in seconds to wait
              schema:
                type: integer
                format: int32
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example: {}
          x-sentenial:
            enriched: "true"
      security:
        - PartnerOAuth2:
            - organisation_admin_read
        - PartnerApiKey: []
        - PartnerGroupApiKey: []
        - PartnerGroupOAuth2:
            - organisation_admin_read
  /organisations/{organisationId}:
    get:
      tags:
        - Organisation Management Service
      summary: Retrieve  Organisation
      description: Retrieve  Organisation
      operationId: retrieveOrganisationUsingGET
      parameters:
        - name: organisationId
          in: path
          description: Encoded Id of organisation to be retrieved
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganisationResponseEnvelope'
              example:
                uri: /organisations/6bee3razby
                data:
                  id: 6bee3razby
                  uri: /organisations/6bee3razby
                  name: Company Limited
                  address:
                    streetName: Four Courts
                    postCode: D02N820
                    townName: Dublin 2
                  country: IE
                  vatID: IE9S99999L
                  customerDefinedReference: 18a7ac1c-410f-4755-9d34-c5de42cdbfff
                  registeredNumber: 32342
                  status: ACTIVE
                  creationDateTime: 2022-05-19T10:32:01Z
                  lastUpdateDateTime: 2022-05-19T11:32:01Z
                  links:
                    - resourceType: openbanking
                      uri: /tpp/organisations/6bee3razby/config
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example: {}
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example: {}
        405:
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example: {}
        429:
          description: Too Many Requests
          headers:
            Retry-After:
              description: Number in seconds to wait
              schema:
                type: integer
                format: int32
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example: {}
          x-sentenial:
            enriched: "true"
      security:
        - MerchantApiKey: []
        - MerchantOAuth2:
            - organisation_admin_read
        - PartnerOAuth2:
            - organisation_admin_read
        - PartnerApiKey: []
        - PartnerGroupOAuth2:
            - organisation_admin_read
        - PartnerGroupApiKey: []
components:
  schemas:
    Address:
      type: object
      properties:
        streetName:
          maxLength: 70
          minLength: 1
          type: string
          description: Name of a street or thoroughfare.
        buildingNumber:
          maxLength: 16
          minLength: 1
          type: string
          description: Number that identifies the position of a building on a street.
        postCode:
          maxLength: 16
          minLength: 1
          type: string
          description: Identifier consisting of a group of letters and/or numbers that is added to a postal address to assist the sorting of mail.
        townName:
          maxLength: 35
          minLength: 1
          type: string
          description: Name of a built-up area, with defined boundaries, and a local government.
        country:
          pattern: ^[A-Z]{2,2}$
          type: string
          description: ISO 3166 ALPHA2 country code.
        addressLine:
          maxItems: 2
          minItems: 0
          type: array
          items:
            description: Information that locates and identifies a specific address, as defined by postal services, presented in free format text.
            maxLength: 70
            minLength: 1
            type: string
      description: Postal Address Details.
    Contact:
      required:
        - email
        - firstName
        - lastName
      type: object
      properties:
        firstName:
          pattern: ^[\\p{L}\\s'-]+$
          maxLength: 35
          type: string
          description: User First Name
        lastName:
          pattern: ^[\\p{L}\\s'-]+$
          maxLength: 35
          type: string
          description: User Last Name
        title:
          type: string
          enum:
            - Mr.
            - Ms.
            - Mrs.
            - Miss.
            - Dr.
            - Prof.
            - Fr.
            - Rev.
            - Bishop
            - Sr.
        mobileNumber:
          maxLength: 30
          pattern: \+[0-9]{1,3}-[0-9()+\-]{1,30}
          type: string
        phoneNumber:
          maxLength: 30
          pattern: \+[0-9]{1,3}-[0-9()+\-]{1,30}
          type: string
        email:
          maxLength: 254
          pattern: .*@.*
          type: string
          description: Debtor Email Address
        language:
          type: string
          description: Communication language
          enum:
            - en
            - pt
            - nl
            - fr
            - it
            - es
            - de
            - sk
            - fr_BE
            - nl_BE
    ErrorResponse:
      title: ErrorResponse
      type: object
      properties:
        details:
          type: array
          description: Holds list of input validation errors
          items:
            $ref: '#/components/schemas/ErrorDetail'
        returnCode:
          type: string
          description: Error type code
        returnDescription:
          type: string
          description: Error type description
    ErrorDetail:
      title: ErrorDetail
      type: object
      description: Holds list of input validation errors
      properties:
        code:
          type: string
          description: Error code
        description:
          type: string
          description: Error description
        field:
          type: string
          description: JSON path to request object property the error is related to
        resourceUri:
          type: string
    OrganisationResponse:
      type: object
      properties:
        id:
          type: string
          description: Resource identifier.
        uri:
          type: string
          description: Resource Uri
        parentId:
          type: string
          description: Parent Organisation Id.
        name:
          maxLength: 70
          type: string
          description: Organisation name
        address:
          $ref: '#/components/schemas/Address'
        contact:
          $ref: '#/components/schemas/Contact'
        vatNumber:
          type: string
          description: VAT ID of the organisation
        customerDefinedReference:
          maxLength: 70
          type: string
          description: Unique reference of the Organisation being created assigned by requesting party.
        registeredNumber:
          description: The Registered Number number of the Organization. This value will vary depending on the country in which the Organization is registered. In general it will be a 'National' Company registration number for tax purposes etc.
          maxLength: 15
          type: string
        status:
          type: string
          description: Organisation status.
          enum:
            - ACTIVE
            - PENDING
            - DISABLED
        organisationType:
          type: string
          description: Organisation type.
          enum:
            - PARTNER_GROUP
            - PARTNER
            - MERCHANT
        creationDateTime:
          type: string
          description: Date and time the Organisation was created.
          format: date-time
        lastUpdateDateTime:
          type: string
          description: Date and time the Organisation status was updated.
          format: date-time
        links:
          type: array
          items:
            $ref: '#/components/schemas/RestResponseLink'
    OrganisationResponseEnvelope:
      type: object
      properties:
        uri:
          type: string
          description: Resource Uri.
        data:
          $ref: '#/components/schemas/OrganisationResponse'
    OrganisationsListResponseEnvelope:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/OrganisationResponse'
        page:
          $ref: '#/components/schemas/RestResponsePaginationDetails'
        sort:
          type: array
          items:
            type: string
        uri:
          type: string
          description: Resource Uri.
    RestResponsePaginationDetails:
      type: object
      properties:
        pageNumber:
          type: integer
          description: Page Number
          format: int32
          default: 1
        pageSize:
          type: integer
          description: Page Size
          format: int32
          default: 20
        totalElements:
          type: integer
          description: Total Number of elements returned. Response parameter only
          format: int32
        totalPages:
          type: integer
          description: Total Number of pages returned. Response parameter only
          format: int32
    RestResponseLink:
      type: object
      properties:
        id:
          type: string
          description: 'Encoded Id of linked resource'
        resourceType:
          type: string
          description: Resource Type
        uri:
          type: string
          description: Resource URI
  securitySchemes:
    MerchantApiKey:
      type: http
      scheme: basic
    PartnerApiKey:
      type: http
      scheme: basic
    PartnerGroupApiKey:
      type: http
      scheme: basic
    MerchantOAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: https://api.nuapay.com/oauth/token_key
          scopes:
            organisation_admin_read: Organisation Management Service Read access
    PartnerOAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: https://api.nuapay.com/oauth/token_key
          scopes:
            organisation_admin_read: Organisation Management Service Read access
    PartnerGroupOAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: https://api.nuapay.com/oauth/token_key
          scopes:
            organisation_admin_read: Organisation Management Service Read access